### ISSUE TITLE
Messages while compiling for Arduino

### ISSUE THREAD

**Issue by apla2016** [thakshak/AM2320#10]
I am trying to compile your example for Arduino Mini and getting the following messages. Any idea what is going on? 
Thank you for your time.

`Arduino: 1.8.13 (Windows 10), Board: "Arduino Pro or Pro Mini, ATmega328P (5V, 16 MHz)"

C:\Users\Administrator\Documents\Arduino\libraries\AM2320\AM2320.cpp: In function 'unsigned int CRC16(byte*, byte)':

C:\Users\Administrator\Documents\Arduino\libraries\AM2320\AM2320.cpp:12:23: error: expected primary-expression before '=' token

                 crc ^ = * ptr++;

                       ^

C:\Users\Administrator\Documents\Arduino\libraries\AM2320\AM2320.cpp:14:42: error: expected ')' before '!' token

                         if ((crc & 0x01) ! = 0) {
                                          ^
C:\Users\Administrator\Documents\Arduino\libraries\AM2320\AM2320.cpp:15:40: error: expected primary-expression before '=' token
                                 crc >> = 1;

                                        ^
C:\Users\Administrator\Documents\Arduino\libraries\AM2320\AM2320.cpp:16:39: error: expected primary-expression before '=' token
                                 crc ^ = 0xA001;
                                       ^
C:\Users\Administrator\Documents\Arduino\libraries\AM2320\AM2320.cpp:17:39: error: expected primary-expression before '=' token
                         } else crc >> = 1;
                                       ^
C:\Users\Administrator\Documents\Arduino\libraries\AM2320\AM2320.cpp: In member function 'int AM2320::Read()':

C:\Users\Administrator\Documents\Arduino\libraries\AM2320\AM2320.cpp:36:37: error: expected ')' before '!' token

         if (Wire.endTransmission(1) ! = 0) return 1;

                                     ^
C:\Users\Administrator\Documents\Arduino\libraries\AM2320\AM2320.cpp:44:16: error: expected primary-expression before '=' token
         Rcrc + = buf[6];

                ^
exit status 1
Error compiling for board Arduino Pro or Pro Mini.
`

**Comment by thakshak** [comment]
Thanks for leaving feedback. Looks like it's the problem with the whitespace between symbols of the operator. Corrected it. Can you please try again and reply here.

**Comment by thakshak** [comment]
> I am trying to compile your example for Arduino Mini and getting the following messages. Any idea what is going on?
> Thank you for your time.
> 
> `Arduino: 1.8.13 (Windows 10), Board: "Arduino Pro or Pro Mini, ATmega328P (5V, 16 MHz)"
> 
> C:\Users\Administrator\Documents\Arduino\libraries\AM2320\AM2320.cpp: In function 'unsigned int CRC16(byte*, byte)':
> 
> C:\Users\Administrator\Documents\Arduino\libraries\AM2320\AM2320.cpp:12:23: error: expected primary-expression before '=' token
> 
> ```
>              crc ^ = * ptr++;
> 
>                    ^
> ```
> 
> C:\Users\Administrator\Documents\Arduino\libraries\AM2320\AM2320.cpp:14:42: error: expected ')' before '!' token
> 
> ```
>                      if ((crc & 0x01) ! = 0) {
>                                       ^
> ```
> 
> C:\Users\Administrator\Documents\Arduino\libraries\AM2320\AM2320.cpp:15:40: error: expected primary-expression before '=' token
> crc >> = 1;
> 
> ```
>                                     ^
> ```
> 
> C:\Users\Administrator\Documents\Arduino\libraries\AM2320\AM2320.cpp:16:39: error: expected primary-expression before '=' token
> crc ^ = 0xA001;
> ^
> C:\Users\Administrator\Documents\Arduino\libraries\AM2320\AM2320.cpp:17:39: error: expected primary-expression before '=' token
> } else crc >> = 1;
> ^
> C:\Users\Administrator\Documents\Arduino\libraries\AM2320\AM2320.cpp: In member function 'int AM2320::Read()':
> 
> C:\Users\Administrator\Documents\Arduino\libraries\AM2320\AM2320.cpp:36:37: error: expected ')' before '!' token
> 
> ```
>      if (Wire.endTransmission(1) ! = 0) return 1;
> 
>                                  ^
> ```
> 
> C:\Users\Administrator\Documents\Arduino\libraries\AM2320\AM2320.cpp:44:16: error: expected primary-expression before '=' token
> Rcrc + = buf[6];
> 
> ```
>             ^
> ```
> 
> exit status 1
> Error compiling for board Arduino Pro or Pro Mini.
> `

Thanks for leaving feedback. Looks like it's the problem with the whitespace between symbols of the operator. Corrected it. Can you please try again and reply here.

**Comment by apla2016** [comment]
Thank you for quick response, problem fixed
