### ISSUE TITLE
Bad conversion in temperature and humidity func

### ISSUE THREAD

**Issue by walkin-corpse** [thakshak/AM2320#3]
We need:
    return (float(temperature)/10);
and
    return (float(humidity)/10);
otherwise we have only integer values for both measurements.

**Comment by oczkers** [comment]
or just
`return(temperature/10.0);`
`return (humidity/10.0);`

**Comment by walkin-corpse** [comment]
Yup, that's more simple.

**Comment by thakshak** [comment]
thankyou.
