### ISSUE TITLE
Change needed to work with ESP8266

### ISSUE THREAD

**Issue by PaulRB** [thakshak/AM2320#5]
Hi, I downloaded and installed your library and uploaded the example sketch, but it causes ESP8266 to give error messages as soon as the sketch begins to run.

Fortunately I have worked out a fix. The problem appears to be caused by this part of file AM2320.cpp:

```
AM2320::AM2320()
{
    Wire.begin();
}
```

I deleted the Wire.begin() from here and put it instead into the setup() function of the example sketch. This stopped the error messages and the example sketch runs OK.

I do not know why having Wire.begin() in this place causes a problem for ESP8266 when it does not cause a problem for other Arduino.

Paul

**Comment by mcauser** [comment]
Hi @PaulRB, the sensor datasheet suggests that the sensor goes to sleep on the I2C bus repetitively.
Around 1-2 seconds on, 1-2 seconds off.
If you run a I2C scan in a loop, you can see it happen.

You are supposed to "ping" the sensor to wake it, and if it is asleep it wont NAK, but if it is awake it will. Once it is awake, it will stay awake for a few seconds before returning to the sleep/wake loop.

I have a AM2320 library in MicroPython running on an ESP8266 (WeMos D1 mini)
https://github.com/mcauser/MicroPython-ESP8266-DHT-Nokia-5110/blob/master/am2320.py

I gathered all of the Aosong datasheets I could find, including this one, and added them here:
https://www.dropbox.com/sh/500lbdxn7hlk4nk/AAAm312r9ESImG0aqd91IXAqa?dl=0

I also compiled specifications for each sensor from various English and Chinese datasheets:
https://docs.google.com/spreadsheets/d/1jbSpU-rLXuba9aubcYI15_6hI2wM7-vmQ4iPcAV7MI4/edit

**Comment by vgheo** [comment]
Hi all,
Using current master (bacb93bb206069c) with [esp8266/Ardiuno](https://github.com/esp8266/Arduino)  on [WeMos D1 Mini](https://www.wemos.cc/product/d1-mini.html) (ESP8266-DX).

Running the provided example, I get the following on the serial monitor (baud=115200) :

```
 ets Jan  8 2013,rst cause:2, boot mode:(1,6)


 ets Jan  8 2013,rst cause:4, boot mode:(1,6)

wdt reset
```

As @PaulRB  pointed out, moving the Wire.begin() call from the constructor to the user's setup() code fixes the problem.

Most probably, in the ESP8266/Arduino implementation, Wire.begin() must be called after some other chip initializations, that have not occured when called from a constructor of a global object.
